# Generated by Django 4.2.4 on 2023-09-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vehicle', 'vehicle'), ('plote', 'plote'), ('house', 'house'), ('building', 'building'), ('land', 'land'), ('others', 'others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='P_image'),
        ),
    ]
