# Generated by Django 4.2.4 on 2023-09-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Au_Date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
