# Generated by Django 4.2.4 on 2023-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_aucart_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Au_Date',
            field=models.DateField(null=True),
        ),
    ]
